### ISSUE TITLE
SocketTimeoutException thrown after POSTing a reply

### ISSUE THREAD

**Issue by Raud0** [xatkit-bot-platform/labs-ut-platform#41]
After sending a reply through the connector, the sockets don't seem to be closed, which causes them to throw a timeout exception. This always happens. It doesn't really affect anything, and the connection is automatically closed. I'm not really sure if this needs to be fixed, but the exception message is ugly regardless.

Might be related, but I turned off logging from `org.apache.http.impl.conn.PoolingHttpClientConnectionManager` for the time being, as it was spamming console with connection timeouts every 30 seconds.
```
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[httpcore-4.4.10.jar:4.4.10]
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153) ~[httpcore-4.4.10.jar:4.4.10]
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282) ~[httpcore-4.4.10.jar:4.4.10]
	at org.apache.http.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:129) ~[httpcore-4.4.10.jar:4.4.10]
	at org.apache.http.impl.io.DefaultHttpRequestParser.parseHead(DefaultHttpRequestParser.java:53) ~[httpcore-4.4.10.jar:4.4.10]
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[httpcore-4.4.10.jar:4.4.10]
	at org.apache.http.impl.DefaultBHttpServerConnection.receiveRequestHeader(DefaultBHttpServerConnection.java:129) ~[httpcore-4.4.10.jar:4.4.10]
	at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:308) ~[httpcore-4.4.10.jar:4.4.10]
	at org.apache.http.impl.bootstrap.Worker.run(Worker.java:66) ~[httpcore-4.4.10.jar:4.4.10]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
02:53:22.792 [Thread-4] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
```

**Comment by Raud0** [comment]
Closing culled issue.
